services:
  mysql_db:
    image: mysql:8.0.16
    environment:
      MYSQL_DATABASE: demo_bank_project
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    restart: always
    ports:
      - '3306:3306'
    expose:
      - 3306
    networks:
      - app_network


  backend_project:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=mysql_db
    ports:
      - '8080:8080'
    depends_on:
      - mysql_db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge